version: "3"
services:
  tomcat:
    image: "tomcat:10.0"
    ports:
      - "8080:8080"
    volumes:
      - ./target/help-service.war:/usr/local/tomcat/webapps/help-service.war
    restart: on-failure